### ISSUE TITLE
Old x-authorization header

### ISSUE THREAD

**Issue by JZNT** [op-developer/python-example-client#1]
The example's old x-authorization header fdb6c7c24bbc3a2c4144c1848825ab7d3a4ccb43 gives an error:

> {u'message': u'Payers Iban not valid', u'type': u'TECHNICAL', u'id': u'<some data here>', u'level': u'ERROR'}
Traceback (most recent call last):
  File "client.py", line 29, in <module>
    confirm = post_requests.payment_confirm(payment['paymentId'], HEADERS)
KeyError: 'paymentId'

From [OP:s page](https://op-developer.fi/docs/#user-content-authentication) the first token "6c18c234b1b18b1d97c7043e2e41135c293d0da9
" did work.

**Comment by TeemuKurki** [comment]
Hi, thanks for telling us. 
I changed x-authorization token to match payer in example. It should work now as expected.
