### ISSUE TITLE
Cannot use find website `https://sandbox.apis.op-palvelut.fi/`

### ISSUE THREAD

**Issue by AlexanderPershin** [op-developer/python-example-client#2]
I've created sandbox app for OP payment tests and cloned and ran this tool. Also I changed `api_key` in source code to that in my app description. However I'm getting `Error: getaddrinfo ENOTFOUND sandbox.apis.op-palvelut.fi` response. Did website move to some other address?

**Comment by TeemuKurki** [comment]
Thanks for letting us know. Yes address has been changed. The address should be sandbox.apis.op.fi instead. This has now been fixed

**Comment by AlexanderPershin** [comment]
Thank you for answering, now it works
